import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: {
    maxWidth: '1000px',
    margin: '0 auto',
    padding: '2rem 1rem',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '2rem',
    flexWrap: 'wrap',
    gap: '1rem',
  },
  title: {
    fontSize: '2rem',
    color: '#ffffff',
    margin: 0,
  },
  subtitle: {
    color: '#a0a0a0',
    margin: '0.4rem 0 0 0',
  },
  createButton: {
    backgroundColor: '#00d2ff',
    color: '#1a1a2e',
    border: 'none',
    padding: '0.6rem 1.2rem',
    borderRadius: '6px',
    fontWeight: 'bold',
    cursor: 'pointer',
    fontSize: '0.95rem',
  },
  errorBox: {
    backgroundColor: 'rgba(233, 69, 96, 0.2)',
    border: '1px solid #e94560',
    color: '#ff6b6b',
    padding: '1rem',
    borderRadius: '6px',
    marginBottom: '1.5rem',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dismissBtn: {
    backgroundColor: 'transparent',
    border: '1px solid #e94560',
    color: '#ff6b6b',
    padding: '0.2rem 0.5rem',
    borderRadius: '4px',
    cursor: 'pointer',
  },
  emptyCard: {
    backgroundColor: '#1a1a2e',
    padding: '3rem',
    textAlign: 'center',
    borderRadius: '8px',
    color: '#a0a0a0',
  },
  tableContainer: {
    backgroundColor: '#1a1a2e',
    borderRadius: '8px',
    overflowX: 'auto',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    color: '#ffffff',
  },
  th: {
    textAlign: 'left',
    padding: '1rem',
    borderBottom: '2px solid rgba(255, 255, 255, 0.1)',
    color: '#00d2ff',
  },
  thRight: {
    textAlign: 'right',
    padding: '1rem',
    borderBottom: '2px solid rgba(255, 255, 255, 0.1)',
    color: '#00d2ff',
  },
  tr: {
    borderBottom: '1px solid rgba(255, 255, 255, 0.05)',
  },
  tdName: {
    padding: '1rem',
    fontWeight: 'bold',
  },
  tdDesc: {
    padding: '1rem',
    color: '#b0b0b0',
  },
  tdRight: {
    padding: '1rem',
    textAlign: 'right',
  },
  editBtn: {
    backgroundColor: '#0f3460',
    color: '#00d2ff',
    border: 'none',
    padding: '0.4rem 0.8rem',
    borderRadius: '4px',
    cursor: 'pointer',
    marginRight: '0.5rem',
    fontWeight: 'bold',
  },
  deleteBtn: {
    backgroundColor: 'rgba(233, 69, 96, 0.2)',
    color: '#ff4d4d',
    border: '1px solid #ff4d4d',
    padding: '0.4rem 0.8rem',
    borderRadius: '4px',
    cursor: 'pointer',
    fontWeight: 'bold',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: '1rem',
  },
  modalContent: {
    backgroundColor: '#1a1a2e',
    padding: '2rem',
    borderRadius: '10px',
    maxWidth: '500px',
    width: '100%',
    boxShadow: '0 4px 20px rgba(0,0,0,0.5)',
    color: '#ffffff',
  },
  modalError: {
    backgroundColor: 'rgba(233, 69, 96, 0.2)',
    color: '#ff6b6b',
    padding: '0.8rem',
    borderRadius: '6px',
    marginBottom: '1rem',
    fontSize: '0.9rem',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.2rem',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.4rem',
  },
  label: {
    fontSize: '0.9rem',
    color: '#a0a0a0',
  },
  input: {
    backgroundColor: '#16213e',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: '6px',
    padding: '0.75rem',
    color: '#ffffff',
    fontSize: '1rem',
  },
  textarea: {
    backgroundColor: '#16213e',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: '6px',
    padding: '0.75rem',
    color: '#ffffff',
    fontSize: '1rem',
    resize: 'vertical',
  },
  modalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '1rem',
    marginTop: '1.5rem',
  },
  cancelBtn: {
    backgroundColor: 'transparent',
    border: '1px solid rgba(255, 255, 255, 0.2)',
    color: '#a0a0a0',
    padding: '0.6rem 1.2rem',
    borderRadius: '6px',
    cursor: 'pointer',
  },
  saveBtn: {
    backgroundColor: '#00d2ff',
    color: '#1a1a2e',
    border: 'none',
    padding: '0.6rem 1.2rem',
    borderRadius: '6px',
    fontWeight: 'bold',
    cursor: 'pointer',
  },
  confirmDeleteBtn: {
    backgroundColor: '#ff4d4d',
    color: '#ffffff',
    border: 'none',
    padding: '0.6rem 1.2rem',
    borderRadius: '6px',
    fontWeight: 'bold',
    cursor: 'pointer',
  },
};
