import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '2rem 1rem',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '2rem',
    flexWrap: 'wrap',
    gap: '1rem',
  },
  title: {
    fontSize: '2rem',
    color: '#ffffff',
    margin: 0,
  },
  subtitle: {
    color: '#a0a0a0',
    marginTop: '0.4rem',
    fontSize: '0.95rem',
  },
  createButton: {
    backgroundColor: '#00d2ff',
    color: '#1a1a2e',
    padding: '0.7rem 1.4rem',
    borderRadius: '6px',
    border: 'none',
    fontWeight: 'bold',
    fontSize: '0.95rem',
    cursor: 'pointer',
  },
  filterSection: {
    display: 'flex',
    gap: '1rem',
    marginBottom: '1.5rem',
    flexWrap: 'wrap',
  },
  searchInput: {
    flex: 1,
    minWidth: '220px',
    backgroundColor: '#1a1a2e',
    border: '1px solid #0f3460',
    color: '#ffffff',
    padding: '0.65rem 1rem',
    borderRadius: '6px',
    outline: 'none',
  },
  selectFilter: {
    backgroundColor: '#1a1a2e',
    border: '1px solid #0f3460',
    color: '#ffffff',
    padding: '0.65rem 1rem',
    borderRadius: '6px',
    outline: 'none',
  },
  errorBox: {
    backgroundColor: 'rgba(220, 53, 69, 0.2)',
    border: '1px solid #dc3545',
    color: '#ff6b6b',
    padding: '1rem 1.2rem',
    borderRadius: '6px',
    marginBottom: '1.5rem',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dismissBtn: {
    backgroundColor: 'transparent',
    border: 'none',
    color: '#ff6b6b',
    cursor: 'pointer',
    fontWeight: 'bold',
    textDecoration: 'underline',
  },
  tableContainer: {
    overflowX: 'auto',
    backgroundColor: '#1a1a2e',
    borderRadius: '8px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.3)',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    textAlign: 'left',
    color: '#ffffff',
  },
  th: {
    backgroundColor: '#0f3460',
    padding: '1rem',
    fontWeight: 600,
    fontSize: '0.9rem',
    color: '#00d2ff',
    borderBottom: '2px solid #16213e',
  },
  thRight: {
    backgroundColor: '#0f3460',
    padding: '1rem',
    fontWeight: 600,
    fontSize: '0.9rem',
    color: '#00d2ff',
    textAlign: 'right',
    borderBottom: '2px solid #16213e',
  },
  tr: {
    borderBottom: '1px solid #16213e',
  },
  tdName: {
    padding: '1rem',
    fontWeight: 600,
  },
  tdCategory: {
    padding: '1rem',
    color: '#00d2ff',
    fontSize: '0.9rem',
  },
  tdDate: {
    padding: '1rem',
    color: '#b0b0b0',
    fontSize: '0.85rem',
  },
  tdLocation: {
    padding: '1rem',
    color: '#e0e0e0',
    fontSize: '0.85rem',
  },
  tdPrice: {
    padding: '1rem',
    fontWeight: 'bold',
    color: '#4ecca3',
  },
  tdCapacity: {
    padding: '1rem',
    color: '#b0b0b0',
    fontSize: '0.85rem',
  },
  tdRight: {
    padding: '1rem',
    textAlign: 'right',
    whiteSpace: 'nowrap',
  },
  editBtn: {
    backgroundColor: '#0f3460',
    color: '#00d2ff',
    border: 'none',
    padding: '0.4rem 0.8rem',
    borderRadius: '4px',
    marginRight: '0.5rem',
    cursor: 'pointer',
    fontWeight: 'bold',
  },
  deleteBtn: {
    backgroundColor: 'rgba(233, 69, 96, 0.2)',
    color: '#e94560',
    border: '1px solid #e94560',
    padding: '0.4rem 0.8rem',
    borderRadius: '4px',
    cursor: 'pointer',
    fontWeight: 'bold',
  },
  emptyCard: {
    backgroundColor: '#1a1a2e',
    padding: '3rem',
    borderRadius: '8px',
    textAlign: 'center',
    color: '#a0a0a0',
  },
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    padding: '1rem',
  },
  modalCard: {
    backgroundColor: '#1a1a2e',
    borderRadius: '10px',
    padding: '2rem',
    width: '100%',
    maxWidth: '650px',
    maxHeight: '90vh',
    overflowY: 'auto',
    boxShadow: '0 10px 25px rgba(0,0,0,0.5)',
    color: '#ffffff',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
    borderBottom: '1px solid #0f3460',
    paddingBottom: '0.8rem',
  },
  modalTitle: {
    margin: 0,
    fontSize: '1.3rem',
    color: '#00d2ff',
  },
  closeBtn: {
    backgroundColor: 'transparent',
    border: 'none',
    color: '#a0a0a0',
    fontSize: '1.5rem',
    cursor: 'pointer',
  },
  deleteCard: {
    backgroundColor: '#1a1a2e',
    borderRadius: '10px',
    padding: '2rem',
    width: '100%',
    maxWidth: '450px',
    textAlign: 'center',
    color: '#ffffff',
  },
  deleteIcon: {
    fontSize: '3rem',
    color: '#e94560',
    marginBottom: '1rem',
  },
  deleteActions: {
    display: 'flex',
    justifyContent: 'center',
    gap: '1rem',
    marginTop: '1.5rem',
  },
  cancelBtn: {
    backgroundColor: 'transparent',
    border: '1px solid #a0a0a0',
    color: '#a0a0a0',
    padding: '0.6rem 1.2rem',
    borderRadius: '6px',
    cursor: 'pointer',
    fontWeight: 'bold',
  },
  confirmDeleteBtn: {
    backgroundColor: '#e94560',
    border: 'none',
    color: '#ffffff',
    padding: '0.6rem 1.2rem',
    borderRadius: '6px',
    cursor: 'pointer',
    fontWeight: 'bold',
  },
};
